# Generated by Django 5.0 on 2023-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_breader_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='breader',
            name='platform',
            field=models.CharField(default='Petfinder', max_length=200),
        ),
    ]
