# Generated by Django 5.0 on 2023-12-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_breader_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breader',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
