# Generated by Django 5.0 on 2023-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_alter_breader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breader',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
