# Generated by Django 5.0 on 2023-12-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0005_alter_breader_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='breader',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
