# Generated by Django 5.0 on 2023-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0006_breader_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breader',
            name='platform',
            field=models.CharField(choices=[('Petfinder', 'Petfinder'), ('AKC', 'AKC')], default='Petfinder', max_length=9),
        ),
    ]
